-- Generated by nwg-displays on 2026-06-30 at 08:56:13. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@60.0",
    position = "3459x1055",
    scale = 1.0
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@60.0",
    position = "1539x1055",
    scale = 1.0
})
