-- Generated by nwg-displays on 2026-06-29 at 19:34:37. Do not edit manually.

hl.monitor({
    output = "DP-1",
    mode = "3440x1440@59.97",
    position = "1920x834",
    scale = 1.0
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@60.0",
    position = "840x638",
    scale = 1.0,
    transform = 1
})
